import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import IntlProvider from "@/providers/IntlProvider";
import { fontClassNames } from "@/ui/fonts";



export const metadata: Metadata = {
    title: "RenomatePro",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
        <head>
            <link
                href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Inter+Tight:wght@600;700;800&display=swap"
                rel="stylesheet"
            />
        </head>
        <body className={`${fontClassNames} font-sans bg-concrete text-secondary`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <IntlProvider>
                {children}
            </IntlProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
